# Generated by Django 3.1.2 on 2022-02-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20220203_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
