# Generated by Django 3.1.2 on 2022-02-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_auto_20220203_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
