# Generated by Django 3.1.2 on 2022-02-04 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_bookcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added',
            field=models.DateField(default=datetime.datetime(2022, 2, 4, 9, 36, 34, 910542, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookapp.bookcategory'),
        ),
        migrations.AddField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 9, 37, 3, 389554, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
