# Generated by Django 3.1.2 on 2022-02-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_borrow_borrowedbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
