# Generated by Django 3.1.2 on 2022-03-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_auto_20220318_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('hard copy', 'Hard copy'), ('reserve', 'Reserve')], max_length=200, null=True),
        ),
    ]
