# Generated by Django 3.1.2 on 2022-03-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0012_auto_20220318_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
