# Generated by Django 3.1.2 on 2022-04-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0014_auto_20220402_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='added',
            new_name='Added',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='desc',
            new_name='BookDescription',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='Publisher',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='updated',
            new_name='Updated',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='uploaded_by',
            new_name='Uploaded_by',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='year',
            new_name='YearPublished',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user_id',
        ),
    ]
