# Generated by Django 3.1.2 on 2022-04-10 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0016_auto_20220411_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='BookDescription',
            new_name='Book_Description',
        ),
    ]
