# Generated by Django 3.1.2 on 2022-04-10 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0017_auto_20220411_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='YearPublished',
            new_name='Year_Published',
        ),
    ]
