# Generated by Django 3.1.2 on 2022-04-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0021_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
