# Generated by Django 3.1.2 on 2022-04-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0022_auto_20220413_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Book_Number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
