# Generated by Django 3.1.2 on 2022-04-16 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0023_book_book_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='Message_To',
            field=models.CharField(blank=True, choices=[('all students', 'All students'), ('publisher', 'Publisher'), ('administor', 'Administor')], default='all students', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
