# Generated by Django 3.1.2 on 2022-04-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0025_auto_20220416_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-posted_at',)},
        ),
    ]
